#!/usr/bin/env bash

# Initialize a counter variable
counter=1

# Use the until loop to display "Best School" 10 times
until [ $counter -gt 10 ]; do
  echo "Best School"
  counter=$((counter + 1))  # Increment the counter
done
